/** HTML rendering happens at build time. No investor data is embedded in the public build. */
export const escapeHtml = (value) => String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const e = escapeHtml;
export const formatNumber = (n) => new Intl.NumberFormat('ru-RU', {minimumFractionDigits: 2, maximumFractionDigits: 2}).format(n).replace('-', '−');
export const CHART_MAX = 140;
export function revenueHeight(value) {
  if (!Number.isFinite(value) || value < 0 || value > CHART_MAX) throw new Error('Выручка вне шкалы диаграммы: ' + value);
  return +(value / CHART_MAX * 100).toFixed(4);
}
function label(text, number = '') { return `<p class="eyebrow">${number ? `<span>${e(number)}</span>` : ''}${e(text)}</p>`; }
function note(text, tone = '') { return `<p class="note ${tone}">${e(text)}</p>`; }
function logo(src) { return `<img class="brand-image" src="${e(src)}" alt="AIS — Asset Integrity Systems" width="598" height="251">`; }
function block(id, body, tone = '') { return `<section id="${id}" class="section ${tone}" aria-labelledby="${id}-title"><div class="container">${body}</div></section>`; }
const arrow = '<span aria-hidden="true">↗</span>';
const sourceLink = (page) => `documents/ais-first-meeting-2026-09-12.pdf#page=${page}`;

export function validateContent(site, investor) {
  if (site?.brand !== 'AIS' || !Array.isArray(site.services) || site.services.length !== 4) throw new Error('Некорректные общие данные AIS.');
  const c = site.contact;
  if (!c || typeof c.email !== 'string' || typeof c.phone !== 'string') throw new Error('Некорректные контакты.');
  if (c.email && !/^[^\s<>"@]+@[^\s<>"@]+\.[^\s<>"@]+$/.test(c.email)) throw new Error('Некорректная почта.');
  if (c.phone && !/^\+?[\d\s()−-]{7,30}$/.test(c.phone)) throw new Error('Некорректный телефон.');
  if (!investor) return;
  if (site.sourceRevision !== investor.sourceRevision) throw new Error('Редакции источников не совпадают.');
  if (investor.years.join(',') !== '2026,2027,2028') throw new Error('Горизонт прогноза изменён; обновите шаблон и проверки.');
  for (const s of Object.values(investor.scenarios)) {
    if (s.revenue.length !== 3 || s.result.length !== 3 || ![...s.revenue,...s.result,s.financingNeed].every(Number.isFinite)) throw new Error('Некорректные данные сценария.');
    s.revenue.forEach(revenueHeight);
  }
  const f = investor.funding;
  if (f.equity + f.loan !== f.total || f.paut + f.ectane + f.workingCapital !== f.total) throw new Error('Источники или использование средств не сходятся.');
}

function renderScenario(key, s, data) {
  return `<section class="scenario-panel" id="scenario-${key}" role="tabpanel" aria-labelledby="tab-${key}" tabindex="0" ${key === 'expanded' ? 'hidden' : ''}>
    <div class="scenario-header"><p>${e(s.tag)}</p><span class="pill">Прогноз · ${e(data.sourceRevision)}</span></div>
    <div class="financial-layout">
      <div class="table-area"><p class="small muted">Все суммы — млн ₽. Выручка без НДС.</p>
        <div class="table-scroll" tabindex="0" role="region" aria-label="Финансовые показатели — ${e(s.label)}">
        <table class="financial-table"><caption class="sr-only">${e(s.label)}: прогноз за 2026–2028 годы</caption><thead><tr><th scope="col">Показатель</th>${data.years.map(y=>`<th scope="col">${y}</th>`).join('')}</tr></thead>
          <tbody><tr><th scope="row">Выручка<br>без НДС</th>${s.revenue.map(v=>`<td>${formatNumber(v)}</td>`).join('')}</tr>
          <tr><th scope="row">Результат<br>после УСН</th>${s.result.map(v=>`<td class="${v < 0 ? 'negative' : 'result'}">${formatNumber(v)}</td>`).join('')}</tr></tbody></table></div>
        <p class="table-hint small muted">На узком экране таблицу можно прокрутить по горизонтали.</p>
        <div class="liquidity-summary"><span>Потребность с резервом по модели</span><strong>${formatNumber(s.financingNeed)} <small>млн ₽</small></strong></div>
        ${key === 'expanded' ? note('Запрос 42 млн ₽ не увеличен автоматически. Для этого сценария с резервом по модели требуется ещё 5,50 млн ₽.', 'warning') : note('42 млн ₽ покрывают расчёт основного варианта с резервом по модели. Возмещаемые перевозки и проживание ещё требуют оценки.')}
      </div>
      <figure class="revenue-chart"><figcaption>Выручка без НДС <span>млн ₽ · единая шкала</span></figcaption>
        <div class="chart-plot"><div class="chart-axis" aria-hidden="true"><span>140</span><span>70</span><span>0</span></div>
          <div class="chart-columns">${data.years.map((year,i)=>`<div class="chart-column"><div class="bar-track"><div class="bar" style="height:${revenueHeight(s.revenue[i])}%" data-value="${s.revenue[i]}" data-scale="${CHART_MAX}"><span>${formatNumber(s.revenue[i])}</span></div></div><b>${year}</b></div>`).join('')}</div>
        </div><p class="small muted">Результат после УСН приведён в таблице. Шкала выручки одинакова для обоих сценариев.</p>
      </figure>
    </div>
  </section>`;
}

function renderEconomics(data, pdf) {
  return block('economics', `${label('Экономика проекта','09')}<div class="section-heading"><h2 id="economics-title">Экономика определённой загрузки,<br>а не оценка всего рынка</h2><p>Показатели исходной модели, без пересчёта доходности или обещаний возврата вложений.</p></div>
    <div class="scenario-tabs" role="tablist" aria-label="Финансовый сценарий">${Object.entries(data.scenarios).map(([key,s])=>`<button type="button" id="tab-${key}" role="tab" aria-controls="scenario-${key}" aria-selected="${key==='base'}" tabindex="${key==='base'?0:-1}" data-scenario="${key}">${e(s.label)}</button>`).join('')}</div>
    ${Object.entries(data.scenarios).map(([key,s])=>renderScenario(key,s,data)).join('')}
    <div class="assumptions" aria-label="Основные предпосылки прогноза"><div><strong>365 дней</strong><p>PAUT: все дни приняты оплачиваемыми, включая ожидание.</p></div><div><strong>90 дней</strong><p>Внутритрубная диагностика в год, начиная с 2027 года.</p></div><div><strong>После УСН</strong><p>С учётом амортизации, до процентов по займу и распределения прибыли.</p></div></div>
    <details class="disclosure"><summary>Дополнительные условия и границы расчёта</summary><div class="details-body"><p>2026 год включает подготовку запуска и два месяца проектных работ. Продление PAUT и инженерных работ на октябрь–декабрь 2028 года является прогнозом.</p><p>Расчётный результат — не банковский остаток, не дивиденды и не гарантированный доход инвестора. Показатели зависят от загрузки, ставок и окончательного состава затрат.</p><p>Воспроизведена редакция модели от ${e(data.sourceRevision)}. До сделки требуется актуализация договорных, кадровых и закупочных вводных. Финансовые вводные подлежат проверке до принятия инвестиционного решения.</p><a class="text-link" href="${e(pdf || sourceLink(11))}" ${pdf ? 'download="AIS_First_Meeting_2026-09-12.pdf"' : 'target="_blank" rel="noopener"'}>Исходный пакет · финансовые таблицы, стр. 11–13 ${arrow}</a></div></details>`);
}
function renderFinancing(data) {
  const f=data.funding;
  const row=(text,amount)=>`<div class="money-row"><span>${e(text)}</span><strong>${amount} <small>млн ₽</small></strong></div>`;
  return block('financing', `${label('Финансирование','10')}<div class="section-heading"><h2 id="financing-title">42 млн ₽ на оборудование<br>и стартовый денежный цикл</h2><p>Источники и использование средств — два разных разреза одного бюджета.</p></div>
    <div class="funding-grid"><article class="funding-card"><h3>Источники финансирования</h3>${row('Долевой вклад инвестора',f.equity)}${row('Заём инвестора',f.loan)}<div class="money-total">Итого <strong>${f.total} млн ₽</strong></div></article>
    <article class="funding-card accent"><h3>Использование средств</h3>${row('Два комплекта SIUI SyncScan 3',f.paut)}${row('Комплект Ectane 3',f.ectane)}${row('Запуск, зарплата, налоги, оборот и резерв',f.workingCapital)}${note('План закупки. Комплектность и окончательные цены уточняются с поставщиками.')}</article></div>
    <div class="cash-cycle"><h3>Работа выполняется раньше оплаты</h3><ol>${['Выполнение работ','Приёмка и счёт','Отсрочка оплаты','Поступление денег'].map(x=>`<li>${e(x)}</li>`).join('')}</ol><p>Базовая отсрочка модели — <strong>${f.paymentDelayDays} дней от счёта</strong>. Затраты на исполнение возникают до оплаты заказчиком.</p></div>
    ${note('Состав резерва определяется моделью. Это не гарантия трёх месяцев покрытия любых расходов. Временное финансирование возмещаемых перевозок и проживания ещё требует оценки.', 'warning')}
    <details class="disclosure"><summary>Предлагаемые условия участия</summary><div class="details-body"><div class="equity-grid"><div><strong>${f.investorShare}%</strong><p>Предлагаемая доля инвестора</p></div><div><strong>20 / 20 / 20%</strong><p>Базовые доли трёх учредителей</p></div><div><strong>${f.loan} млн ₽</strong><p>Отдельный заём, не вклад за долю</p></div></div><p>Ставка, сроки и график возврата займа согласуются отдельно. В текущем прогнозе возврат и проценты не начислены. Распределение прибыли не заменяет исполнение обязательств компании.</p></div></details>`, 'tone-light');
}

export function renderPage(site, investor, options = {}) {
  validateContent(site, investor);
  const privateEdition=Boolean(investor);
  const image=options.logoData || 'assets/ais-monogram.png';
  const nav=privateEdition ? [['Подход','approach'],['Услуги','services'],['Команда','team'],['Проекты','projects'],['Экономика','economics'],['План запуска','launch']] : [['Подход','approach'],['Услуги','services'],['Задачи','tasks'],['Команда','team']];
  const navHtml=nav.map(([name,id])=>`<a href="#${id}" data-nav="${id}">${name}</a>`).join('');
  const contact=site.contact;
  const contactHasChannel=Boolean(contact.email||contact.phone);
  const pdfHref=options.pdfData||'documents/ais-first-meeting-2026-09-12.pdf';
  const labelMode=privateEdition?'Инженерная компания · Инвестиционный проект':'Проект инженерной компании';
  const sourceRef=privateEdition?`<a class="source-link" href="${e(pdfHref)}" ${options.pdfData?'download="AIS_First_Meeting_2026-09-12.pdf"':'target="_blank" rel="noopener"'}>Материалы от ${e(site.sourceRevision)}</a>`:'';
  const body=`
<a class="skip-link" href="#main">Перейти к содержанию</a>
<header class="site-header"><div class="container header-inner"><a class="brand" href="#top" aria-label="AIS — к началу страницы">${logo(image)}</a><nav class="desktop-nav" aria-label="Основная навигация">${navHtml}</nav><a class="button button-small header-cta" href="#contact">Обсудить проект</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-navigation" aria-label="Открыть меню"><span aria-hidden="true">☰</span><span>Меню</span></button></div><nav class="mobile-nav" id="mobile-navigation" aria-label="Мобильная навигация">${navHtml}<a href="#contact">Обсудить проект</a></nav><div class="reading-progress" aria-hidden="true"></div></header>
<main id="main" tabindex="-1">
<section id="top" class="hero" aria-labelledby="hero-title"><div class="container"><div class="hero-grid"><div class="hero-copy">${label(labelMode)}<h1 id="hero-title">${e(site.hero.title)}<br><span>${e(site.hero.accent)}</span></h1><p class="hero-intro">${e(site.hero.intro)}</p><p class="hero-detail">${e(privateEdition?site.hero.detail:'Связываем инженерную подготовку, полевой контроль и проверку результатов. Развиваем направления под конкретные задачи заказчиков.')}</p><div class="button-row"><a class="button" href="#approach">${privateEdition?'Рассмотреть проект':'Наш подход'} ${arrow}</a><a class="button button-outline" href="#${privateEdition?'economics':'services'}">${privateEdition?'Экономика запуска':'Направления работы'}</a></div></div>
<aside class="engineering-plate" aria-label="Последовательность инженерной работы"><div class="plate-heading"><span>AIS / ПОДХОД</span><span class="plate-dot" aria-hidden="true"></span></div><div class="plate-object"><div class="object-rings" aria-hidden="true"><i></i><i></i><i></i><b></b></div><div><span class="small">Отправная точка</span><strong>Оборудование<br>и его состояние</strong></div></div><ol class="plate-steps">${[['01','Понять условия','Материал · среда · история'],['02','Получить данные','Программа · метод · измерения'],['03','Проверить результат','Прослеживаемость · ограничения']].map(([n,t,d])=>`<li><span>${n}</span><div><strong>${t}</strong><small>${d}</small></div></li>`).join('')}</ol><p class="plate-footer">Следующая инспекция опирается<br>на предыдущую.</p></aside></div>
${privateEdition?`<div class="hero-facts"><div><strong>2 команды PAUT</strong><span>стартовая программа</span></div><div><strong>90 дней</strong><span>план диагностики теплообменников в год</span></div><div><strong>42 млн ₽</strong><span>предлагаемое финансирование</span></div></div><p class="hero-caption">Параметры планируемого запуска, не текущие достижения компании.</p>`:`<div class="hero-facts compact"><div><strong>Подготовка</strong><span>задача и программа инспекции</span></div><div><strong>Контроль</strong><span>измерения по согласованной технологии</span></div><div><strong>Данные</strong><span>проверяемая история состояния</span></div></div>`}
</div></section>
${block('approach',`${label('Задача заказчика','02')}<div class="split"><div><h2 id="approach-title">${e(site.problem.title)}</h2><p class="lead">${e(site.problem.text)}</p><p class="statement">AIS связывает эти задачи в одну последовательность работ.</p></div><ol class="questions">${site.problem.questions.map(([q,d],i)=>`<li><span class="number">0${i+1}</span><div><h3>${e(q)}</h3><p>${e(d)}</p></div></li>`).join('')}</ol></div>`)}
${block('cycle',`${label('Инженерный подход','03')}<div class="split unequal"><div><h2 id="cycle-title">Один объект.<br>Связанный цикл инспекций</h2><p class="lead">Эксплуатационные решения остаются за заказчиком. AIS отвечает за качество своей инженерной и диагностической работы.</p>${note('Цикл повторяется. Каждая инспекция опирается на предыдущую.')}</div><ol class="process">${site.process.map(([title,text],i)=>`<li><span class="number">0${i+1}</span><div><h3>${e(title)}</h3><p>${e(text)}</p></div></li>`).join('')}</ol></div>`, 'tone-light')}
${block('services',`${label('Что предлагает AIS','04')}<div class="section-heading"><h2 id="services-title">Четыре направления<br>одной инженерной задачи</h2></div><div class="service-grid">${site.services.map((s,i)=>`<article class="service-card"><div class="service-top"><span class="service-number">0${i+1}</span><span class="service-methods">${e(s.methods)}</span></div><h3>${e(s.title)}</h3><p>${e(s.body)}</p><div class="service-result"><strong>Результат для заказчика</strong><p>${e(s.result)}</p></div></article>`).join('')}</div>${note('Самостоятельная экспертиза промышленной безопасности не входит в стартовую деятельность.')}`)}
${block('tasks',`${label('Прикладные инженерные задачи','05')}<div class="section-heading"><h2 id="tasks-title">Где нужен не только прибор,<br>но и инженерная подготовка</h2><p>Примеры задач и планируемых подходов — не выполненные кейсы AIS.</p></div><div class="task-grid">${site.tasks.map((x,i)=>`<article class="task-card"><span class="task-mark" aria-hidden="true">0${i+1}</span><h3>${e(x.title)}</h3><p>${e(x.body)}</p>${x.note?note(x.note,'warning'):''}</article>`).join('')}</div>`, 'tone-dark')}
${privateEdition ? block('program',`${label('Стартовая программа','06')}<div class="section-heading"><h2 id="program-title">Начинаем с определённого<br>состава работ</h2><p>Для чередования двух смен PAUT предусмотрено десять специалистов; одновременно на объекте — пять.</p></div><div class="program-grid">${investor.program.map((x,i)=>`<article class="program-card"><span class="pill">${i===2?'Кампания':'Постоянная позиция — план'}</span><h3>${e(x.title)}</h3><ul>${x.lines.map(t=>`<li>${e(t)}</li>`).join('')}</ul></article>`).join('')}</div><div class="expansion-callout"><strong>Шесть инженеров — отдельный сценарий</strong><p>При обеспеченном заказе и оборотном капитале, без автоматического включения в основной вариант.</p></div>${note('Непрерывная оплата PAUT — предпосылка финансовой модели, не подписанное обязательство заказчика.')}`, 'tone-light'):''}
${block('team',`${label('Команда и качество','07')}<div class="split"><div><h2 id="team-title">Персональная ответственность<br>за исполнение и данные</h2><p class="lead">Компания объединяет личный профессиональный опыт участников команды на крупных нефтегазовых объектах. Он является основой подхода, но не заменяет историю контрактов новой компании.</p><div class="team-list">${site.team.map(x=>`<article class="team-member"><span class="initials" aria-hidden="true">${e(x.initials)}</span><div><h3>${e(x.name)}</h3><p class="member-role">${e(x.role)}</p><p>${e(x.detail)}</p></div></article>`).join('')}</div></div><div class="quality-card"><h3>Контрольные точки</h3><ol>${site.quality.map((x,i)=>`<li><span>0${i+1}</span><p>${e(x)}</p></li>`).join('')}</ol><div class="quality-bottom"><span class="small">До передачи заказчику</span><strong>Проверяем не только отчёт,<br>но и основание вывода.</strong></div></div></div>`)}
${privateEdition?block('projects',`${label('Выход на проекты','08')}<div class="split"><div><h2 id="projects-title">Первый шаг — специализированная работа через действующих подрядчиков</h2><p class="lead">Планируем начинать с задач, для которых генеральным подрядчикам нужны профильные команды, техническая подготовка и проверяемый результат. Расширение связываем с фактическими заказами и условиями оплаты.</p><p>Основной коммерческий аргумент — подготовленные специалисты, качество данных, технологическая готовность и контроль исполнения.</p></div><div><ol class="project-list">${investor.projects.map(([name,detail],i)=>`<li><span class="number">0${i+1}</span><div><h3>${e(name)}</h3><p>${e(detail)}</p></div></li>`).join('')}</ol>${note('По сведениям учредителей проведены предварительные переговоры. Перечисленные проекты не являются подтверждённым портфелем заказов AIS.','warning')}</div></div>`,'tone-light'):''}
${privateEdition?renderEconomics(investor,options.pdfData):''}
${privateEdition?renderFinancing(investor):''}
${privateEdition?block('launch',`${label('План запуска и условия роста','11')}<div class="section-heading"><h2 id="launch-title">Расширяемся под заказы,<br>а не ради размера компании</h2><p>Все даты — план из материалов первой встречи, а не подтверждение выполненных этапов.</p></div><div class="split unequal"><aside class="growth-conditions"><h3>Проверяем до расширения</h3><ul>${['Объём и условия заказа','Полную стоимость исполнения','Сроки поступления денег','Готовность специалистов и оборудования'].map(x=>`<li>${x}</li>`).join('')}</ul></aside><ol class="timeline">${investor.milestones.map(([date,title,text])=>`<li><div class="timeline-date">${e(date)}</div><div><h3>${e(title)}</h3><p>${e(text)}</p></div></li>`).join('')}</ol></div>${note('Акустическая эмиссия, ACFM, MFL и дистанционные обследования — направления развития, а не уже укомплектованные стартовые услуги.')}`):''}
${block('contact',`${label(privateEdition?'Предмет встречи':'Обсуждение задачи',privateEdition?'12':'08')}<div class="split"><div><h2 id="contact-title">${privateEdition?'Обсудим запуск AIS<br>и условия участия':'Обсудим инженерную задачу'}</h2><p class="lead">${privateEdition?'Предлагаем согласовать стартовую программу, структуру финансирования и условия, при которых проект переходит от подготовки к выполнению работ.':'Начинаем с исходных сведений об оборудовании, задачи обследования и ожидаемого результата. Состав и условия работ определяются отдельно.'}</p><ol class="meeting-points">${(privateEdition?['Объём первой программы и подрядный канал','Оборудование и оборотное финансирование','Условия участия и контроль использования средств']:['Объект и задача обследования','Исходные данные, доступы и ограничения','Состав результата и порядок выполнения']).map(x=>`<li>${x}</li>`).join('')}</ol><div class="button-row">${contact.email?`<a class="button" href="mailto:${e(contact.email)}">Написать по проекту ${arrow}</a>`:''}${privateEdition?`<button class="button ${contact.email?'button-outline':''}" type="button" data-open-materials>Материалы первой встречи ${arrow}</button>`:''}<button class="button button-outline print-button" type="button" data-print>Версия для печати</button></div></div><aside class="contact-card"><h3>Контакт по проекту</h3><p class="contact-name">${e(contact.name)}</p><p>${e(contact.role)}</p>${contact.phone?`<a class="contact-link" href="tel:${e(contact.phone.replace(/[^+\d]/g,''))}">${e(contact.phone)}</a>`:''}${contact.email?`<a class="contact-link" href="mailto:${e(contact.email)}">${e(contact.email)}</a>`:''}${!contactHasChannel?'<p class="contact-note">Телефон и почта для внешней публикации пока не указаны. Для связи используйте контакт представителя, передавшего презентацию.</p>':''}<div class="contact-status"><span class="status-dot" aria-hidden="true"></span>Проект создания инженерной компании</div></aside></div>`,'tone-dark')}
</main>
<footer class="site-footer"><div class="container"><div class="footer-main"><a class="brand" href="#top" aria-label="AIS — к началу страницы">${logo(image)}</a><p>Инженерная подготовка.<br>Специализированный контроль. Проверенные данные.</p><div>${sourceRef}<span class="footer-version">${privateEdition?'Для обсуждения с инвестором':'Информационная версия проекта'}</span></div></div><p class="footer-legal">AIS — Asset Integrity Systems. Проект создания инженерной компании. ${privateEdition?'Материал подготовлен для адресного обсуждения с инвесторами и стратегическими партнёрами. Данные являются плановыми и прогнозными, а не подтверждённым портфелем заказов.':'Представленные направления не означают наличия всех необходимых приборов, разрешений и заключённых договоров.'}</p></div></footer>
${privateEdition?`<dialog id="materials-dialog" class="materials-dialog" aria-labelledby="materials-title"><div class="dialog-heading"><h2 id="materials-title">Материалы первой встречи</h2><button type="button" class="dialog-close" data-close-materials aria-label="Закрыть материалы">×</button></div><p>Исходный пакет СЦА · редакция ${e(site.sourceRevision)} · 29 страниц.</p><ul class="materials-list"><li><span>00</span>Описание инвестиционного пакета</li><li><span>01</span>Бизнес-план</li><li><span>Ф</span>Финансовая выжимка</li><li><span>11</span>Техническая идея и модель работы</li></ul><a class="button" href="${e(pdfHref)}" download="AIS_First_Meeting_2026-09-12.pdf">Сохранить исходный PDF <span aria-hidden="true">↓</span></a><p class="small muted">PDF передаётся без редактирования. Финансовая модель Excel в материалы сайта не включена.</p></dialog>`:''}
<noscript><style>.scenario-panel[hidden]{display:block!important}.scenario-tabs,.menu-toggle,[data-open-materials],.print-button{display:none!important}</style><div class="noscript-message">JavaScript отключён. ${privateEdition?`Оба сценария показаны последовательно. <a href="${e(pdfHref)}" download="AIS_First_Meeting_2026-09-12.pdf">Исходные материалы PDF</a>.`:'Все основные разделы доступны.'}</div></noscript>`;
  return {body, title: `AIS — Asset Integrity Systems · ${privateEdition?'Инвестиционный проект':'Инженерная компания'}`, description: 'Инженерная подготовка, специализированный неразрушающий контроль и проверенные инспекционные данные.', audience: privateEdition?'investor':'public'};
}
