import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {build,ROOT,standalone} from '../scripts/build.mjs';
import {escapeHtml,formatNumber,revenueHeight,renderPage,validateContent} from '../scripts/render.mjs';
import {safePath,startServer} from '../scripts/serve.mjs';
const read=path=>readFile(join(ROOT,path),'utf8');
const hash=b=>createHash('sha256').update(b).digest('hex');
let site,investor,privateHtml,publicHtml,server,url;
before(async()=>{
 site=JSON.parse(await read('content/site.json'));investor=JSON.parse(await read('content/investor.json'));
 await build('investor');await build('public');
 privateHtml=await read('dist-investor/index.html');publicHtml=await read('dist-public/index.html');
 server=await startServer({root:join(ROOT,'dist-investor'),port:0});url=`http://127.0.0.1:${server.address().port}`;
});
after(async()=>{if(server)await new Promise(resolve=>server.close(resolve));});
test('Финансовые значения основного варианта сохранены',()=>{
 assert.deepEqual(investor.scenarios.base.revenue,[14.01,92.68,92.68]);
 assert.deepEqual(investor.scenarios.base.result,[-0.03,31.57,30.23]);
 assert.equal(investor.scenarios.base.financingNeed,37.65);
});
test('Финансовые значения расширения сохранены',()=>{
 assert.deepEqual(investor.scenarios.expanded.revenue,[18.88,121.87,121.87]);
 assert.deepEqual(investor.scenarios.expanded.result,[1.34,40.16,38.22]);
 assert.equal(investor.scenarios.expanded.financingNeed,47.5);
});
test('Показан вклад инвестора, а не учредителей',()=>{assert.ok(privateHtml.includes('Долевой вклад инвестора'));assert.ok(!privateHtml.includes('Долевой вклад учредителей'));});
test('Источники и назначение средств сходятся',()=>{const f=investor.funding;assert.equal(f.equity+f.loan,42);assert.equal(f.paut+f.ectane+f.workingCapital,42);});
test('Отрицательный результат и десятичная запятая сохранены',()=>{assert.equal(formatNumber(-0.03),'−0,03');assert.ok(privateHtml.includes('class="negative">−0,03'));});
test('Единая нулевая шкала графика для обоих сценариев',()=>{assert.equal(revenueHeight(140),100);assert.equal(revenueHeight(0),0);assert.equal(revenueHeight(70),50);assert.equal((privateHtml.match(/data-scale="140"/g)||[]).length,6);});
test('Отрицательная выручка не рисуется через абсолютное значение',()=>assert.throws(()=>revenueHeight(-1)));
test('Недопустимые числа не проходят в диаграмму',()=>{for(const x of [NaN,Infinity,141])assert.throws(()=>revenueHeight(x));});
test('Ключевые условия не спрятаны в details',()=>{const alwaysVisible=privateHtml.replace(/<details[\s\S]*?<\/details>/g,'');for(const s of ['365 дней','90 дней','до процентов по займу'])assert.ok(alwaysVisible.includes(s));});
test('Уникальные id страницы',()=>{const ids=[...privateHtml.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);});
test('Все якоря ведут в существующий раздел',()=>{for(const m of privateHtml.matchAll(/href="#([^"]+)"/g))assert.ok(privateHtml.includes(`id="${m[1]}"`),m[1]);});
test('Команда ведёт к участникам, не стартовой программе',()=>assert.match(privateHtml,/<section id="team"[\s\S]*?Бабынин А\.В\./));
test('Служебная фраза о регистрации удалена',()=>{assert.ok(!privateHtml.includes('находится в стадии регистрации'));assert.ok(privateHtml.includes('Проект создания инженерной компании'));});
test('Ни ложной отправки формы, ни mailto-заглушки',()=>{assert.ok(!privateHtml.includes('mailto:[email]'));assert.ok(!privateHtml.includes('<form'));assert.ok(!privateHtml.includes('href="mailto:'));});
test('Контакты можно задать без изменения шаблона',()=>{const data=structuredClone(site);data.contact.email='project@example.com';data.contact.phone='+7 (900) 123-45-67';const html=renderPage(data,investor).body;assert.ok(html.includes('mailto:project@example.com'));assert.ok(html.includes('tel:+79001234567'));});
test('Контакты с HTML/JS отвергаются',()=>{const data=structuredClone(site);data.contact.email='javascript:alert(1)';assert.throws(()=>renderPage(data,investor));});
test('Пользовательские строки экранируются',()=>assert.equal(escapeHtml('<script>"&\''),'&lt;script&gt;&quot;&amp;&#39;'));
test('Несогласованная редакция отклоняется',()=>{const i=structuredClone(investor);i.sourceRevision='01.01.2000';assert.throws(()=>validateContent(site,i));});
test('Неполные финансовые массивы отклоняются',()=>{const i=structuredClone(investor);i.scenarios.base.revenue.pop();assert.throws(()=>validateContent(site,i));});
test('В публичном HTML нет инвесторских разделов или значений',()=>{for(const x of ['id="economics"','id="financing"','121,87','92,68','47,50','Долевой вклад','Заём инвестора','40%','Сахалин-1','ТШО','29 страниц'])assert.ok(!publicHtml.includes(x),x);});
test('В публичной сборке нет PDF, исходников и финансового JSON',async()=>{const paths=await readdir(join(ROOT,'dist-public'),{recursive:true});assert.ok(!paths.some(x=>/\.pdf$|investor\.json|\.tsx$|\.xlsx$|^reference|^content|^private-assets/.test(x)));});
test('Общий клиентский код не содержит финансовых значений',async()=>{const js=await read('dist-public/assets/app.js');assert.ok(!/92\.68|121\.87|47\.50|31\.57/.test(js));});
test('Индексирование по умолчанию выключено в обеих редакциях',async()=>{for(const h of [privateHtml,publicHtml])assert.ok(h.includes('content="noindex,nofollow"'));assert.match(await read('dist-public/robots.txt'),/Disallow: \//);});
test('Нет зависимости от Figma, CDN или внешних шрифтов',async()=>{const combined=privateHtml+await read('dist-investor/assets/styles.css')+await read('dist-investor/assets/app.js');assert.ok(!/https?:\/\//.test(combined));assert.ok(!combined.includes('.figma/make/site.json'));});
test('Утверждённая монограмма используется байт-в-байт',async()=>assert.equal(hash(await readFile(join(ROOT,'assets/ais-monogram.png'))),hash(await readFile(join(ROOT,'dist-investor/assets/ais-monogram.png')))));
test('PDF передан байт-в-байт',async()=>assert.equal(hash(await readFile(join(ROOT,'private-assets/ais-first-meeting-2026-09-12.pdf'))),hash(await readFile(join(ROOT,'dist-investor/documents/ais-first-meeting-2026-09-12.pdf')))));
test('Ресурсы используют относительные пути для подкаталога Pages',()=>{const links=[...privateHtml.matchAll(/(?:href|src)="([^"]+)"/g)].map(m=>m[1]);assert.ok(!links.some(x=>x.startsWith('/')));});
test('CSP отключает соединения и серверную отправку',()=>{assert.ok(privateHtml.includes("connect-src &#39;none&#39;"));assert.ok(privateHtml.includes("form-action &#39;none&#39;"));});
test('Локальный сервер выдаёт страницу',async()=>{const r=await fetch(url);assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/text\/html/);});
test('Локальный сервер выдаёт PDF без преобразования',async()=>{const r=await fetch(url+'/documents/ais-first-meeting-2026-09-12.pdf');assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/pdf');const b=Buffer.from(await r.arrayBuffer());assert.equal(b.subarray(0,5).toString(),'%PDF-');});
test('Локальный сервер не обслуживает исходники',async()=>{assert.equal((await fetch(url+'/content/investor.json')).status,404);});
test('Локальный сервер не принимает формы',async()=>assert.equal((await fetch(url,{method:'POST',body:'x'})).status,405));
test('Обход корня, скрытые файлы и некорректные пути блокируются',()=>{for(const p of ['/../content/site.json','/%2e%2e/secret','/.git/config','/%00','/%gg','/foo\\bar'])assert.equal(safePath('/site',p),null);});
test('Манифест честно указывает отсутствие аутентификации',async()=>assert.equal(JSON.parse(await read('dist-investor/build-manifest.json')).authentication,false));
test('Сборка воспроизводима',async()=>{const before=await read('dist-public/build-manifest.json');await build('public');assert.equal(await read('dist-public/build-manifest.json'),before);});
test('Невалидный режим сборки не пишет файлы',async()=>await assert.rejects(()=>build('private')));
